-- Add missing columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS mobile VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS mobile_verified CHAR(1) DEFAULT 'N' CHECK (mobile_verified IN ('Y', 'N'));
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_code VARCHAR(6);
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_expiry TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_sent_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_verified CHAR(1) DEFAULT 'N' CHECK (otp_verified IN ('Y', 'N'));
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_resend_count INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_last_resend_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sms_count_today INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sms_last_sent_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS isactive CHAR(1) DEFAULT 'Y' CHECK (isactive IN ('Y', 'N'));
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP;